jobs:
- name: anynines_blog_build_job
  plan:
  - get: anynines_blog_dockerfile
    trigger: true
  - put: anynines_blog_build_image
    params: {build: anynines_blog_dockerfile}
resources:
- name: anynines_blog_dockerfile
  type: git
  source:
   uri: https://github.com/poojamuralidharan/hello-world.git
   branch: master
   paths: [Dockerfile]
      
- name: anynines_blog_build_image
  type: docker-image
  source:
   repository: bguttmannavtq/anynines-blog-build-image
   email: pooja258mm@gmail.com
   username: pooja258mm
   password: pooja*1234
